CREATE OR REPLACE TABLE COMMODITY_PRICE (
    COMMODITY      VARCHAR(100) NOT NULL,
    PRICE_PER_KG   NUMBER(10,2) NOT NULL,
    CURRENCY       VARCHAR(10) NOT NULL,
    LAST_UPDATED   TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);