
CREATE DATABASE IF NOT EXISTS ATMOSYNC_DB;

USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS RAW_DATA;

USE SCHEMA RAW_DATA;

CREATE TABLE IF NOT EXISTS CONTAINER_SENSOR_DATA
(
    CONTAINER_ID STRING,
    COMMODITY STRING,
    LOCATION STRING,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    VIBRATION FLOAT,
    BATTERY_LEVEL NUMBER,
    SENSOR_STATUS STRING,
    EVENT_TIME TIMESTAMP
);