CREATE OR REPLACE TABLE CONTAINER_SENSOR_DATA
(
    CONTAINER_ID STRING,
    COMMODITY STRING,
    LOCATION STRING,

    SOURCE_PORT STRING,
    DESTINATION_PORT STRING,

    LATITUDE FLOAT,
    LONGITUDE FLOAT,

    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    VIBRATION FLOAT,
    SPEED FLOAT,

    BATTERY_LEVEL INTEGER,

    DOOR_STATUS STRING,
    GPS_STATUS STRING,
    NETWORK_STATUS STRING,

    EVENT_TYPE STRING,

    SENSOR_STATUS STRING,

    EVENT_TIME TIMESTAMP
);